import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import QueryProvider from "@/lib/providers/QueryProvider";
import MobileFooter from "@/components/MobileFooter";
import MobileHeader from "@/components/MobileHeader";
import RegisterServiceWorker from "@/components/RegisterServiceWorker";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Campamento Andino Sayhueque",
  description: "Sistema de gestión del Campamento Andino Sayhueque",
  icons: {
    icon: [
      { url: '/logo-192.png' },
      { url: '/logo-192.png', rel: 'apple-touch-icon' },
    ],
    other: [
      {
        rel: 'mask-icon',
        url: '/logo.svg',
        color: '#FF6B35',
      },
      {
        rel: 'icon',
        url: '/logo-192.png',
      }
    ],
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
  },
  // Next.js will automatically inject the link to the manifest generated by manifest.ts
};

export const viewport: Viewport = {
  themeColor: "#FF6B35",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="h-full" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <AuthProvider>
          <QueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <RegisterServiceWorker />
              <Toaster richColors position="top-center" />
              {/* Estructura con Grid Layout - sin spacers huérfanos */}
              <div className="h-full grid grid-rows-[auto_1fr_auto] md:grid-rows-[auto_1fr]">
                {/* Header Mobile - solo visible en móviles */}
                <MobileHeader />
                
                {/* Header Desktop - parte del flujo del grid */}
                <MobileFooter />

                {/* Contenido principal - ocupa el espacio restante (1fr) */}
                <main className="overflow-auto">{children}</main>

                {/* Footer Mobile se maneja dentro de MobileFooter con fixed positioning */}
              </div>
            </ThemeProvider>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
