# Este archivo ahora crea previsualizaciones en el proyecto correcto
# según la rama de destino del PR (main, dev, o qa).

name: Deploy to Firebase Hosting on PR

on: pull_request

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    # Esta condición de seguridad es buena, la mantenemos
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build

      # --- Lógica de Previsualización por Entorno ---

      # Despliega un PREVIEW en el proyecto de PRODUCCIÓN
      # si el Pull Request apunta a la rama 'main'
      - name: Deploy Preview to Production Environment
        if: github.base_ref == 'main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CAS_WEB_465521 }}
          projectId: cas-web-465521

      # Despliega un PREVIEW en el proyecto de DESARROLLO
      # si el Pull Request apunta a la rama 'dev'
      - name: Deploy Preview to Development Environment
        if: github.base_ref == 'dev'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CAS_WEB_465521 }}
          projectId: authzen-gma61

      # Despliega un PREVIEW en el proyecto de QA
      # si el Pull Request apunta a la rama 'qa'
      - name: Deploy Preview to QA Environment
        if: github.base_ref == 'qa'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CAS_WEB_465521 }}
          projectId: sample-firebase-ai-app-55ff6